### ISSUE TITLE
sqlite3 nodejs

### ISSUE THREAD

**Issue by dkutsanov** [xbolshe/galileo-custom-images#1]
I have an issue when I build a very simple nodejs server with sqlite3 module.

I saw the documentation of sqlite and it depends on node-gyp which depends on:
python (v2.7 recommended, v3.x.x is not supported) (python version on this image is >3)
make (this is ok)
A proper C/C++ compiler toolchain, like GCC (and there is no gcc)

Is there any way to solve this?

BR,
dimak

**Comment by xbolshe** [comment]
In the last image version I have added GCC.
This and previous images have 2 python installed: 3.3.3 and 2.7.3
node-gyp and sqlite3/node-sqlite3 are pre-installed as well as nodejs in the images.

BR,
xbolshe

**Comment by dkutsanov** [comment]
Now it works properly. Thank you.
