### ISSUE TITLE
How do I run a script at start up?

### ISSUE THREAD

**Issue by AntonioAlgaida** [xbolshe/galileo-custom-images#3]
I have a script in a folder:

`/media/mmc.../script.sh`

I need this script to run every time the system starts.

The various options that the [community](http://askubuntu.com/questions/228304/how-do-i-run-a-script-at-start-up) has proposed can not be performed because missing files have to edit the script to launch at startup.
What do I need to do in order to make this happen?

A greeting.
AntonioG

**Comment by xbolshe** [comment]
I guess you may try to create own start-up service using systemd.
Another [community](http://unix.stackexchange.com/questions/47695/how-to-write-startup-script-for-systemd) may help.

BR,
xbolshe

**Comment by AntonioAlgaida** [comment]
Hi Xbolshe:

I followed the steps its put them on the [link](http://unix.stackexchange.com/questions/47695/how-to-write-startup-script-for-systemd).
I also watched [this](http://ianbarton.net/posts/2014/Mar/27/creating-a-wireless-access-point-using-a-raspberrypi-and-a-mobile-phone/).
I have the service: 
`/etc/systemd/system/ap-setup.service`

This:

```
[Unit]
Description=Ap-Setup
Before=hostapd.service
Wants=network.target
Before=network.target
BindsTo=sys-subsystem-net-devices-wlp1s0.device
After=sys-subsystem-net-devices-wlp1s0.device

[Service]
Type=oneshot
ExecStart=/media/realroot/ap-setup.sh

[Install]
WantedBy=multi-user.target
```

My script is in:
`/media/realroot/ap-setup.sh`

And this inside:

```
#!/bin/sh

sleep 5
systemctl stop wpa_supplicant
iw reg set ES
rfkill unblock wifi
ifconfig wlp1s0 192.168.200.1
hostapd -B /etc/hostapd.conf
udhcpd &

```

and finally:
`systemctl enable ap-setup.service`

But still does not work, what do I do wrong?

**Comment by xbolshe** [comment]
As I see on a picture below, systemd allows to run a script at start up. 
So, there is no script start up issue.

![tests3](https://cloud.githubusercontent.com/assets/10796236/15276098/8b16aab6-1ae6-11e6-8fda-447a5691a0a3.png)

**Comment by xbolshe** [comment]
I guess need to debug a script to find a reason why it does not work in your case.
