### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by AntonioAlgaida** [xbolshe/galileo-custom-images#4]
I am trying to install a driver for USB wifi TP-LINK Archer T4U AC1200
The driver is from [abperiasamy](https://github.com/abperiasamy/rtl8812AU_8821AU_linux):
https://github.com/abperiasamy/rtl8812AU_8821AU_linux

The error that occurs to me is:

`root@quark:~/rtl8812AU_8821AU_linux-master# make`
`make ARCH=i386 CROSS_COMPILE= -C /lib/modules/3.19.8-yocto-standard/build` `M=/home/root/rtl8812AU_8821AU_linux-master  modules`
`make[1]: *** /lib/modules/3.19.8-yocto-standard/build: No such file or directory.  Stop.`
`Makefile:1049: recipe for target 'modules' failed`
`make: *** [modules] Error 2`

I tried to create the folder manually myself, but I still occurs the following error.

`root@quark:~/rtl8812AU_8821AU_linux-master# mkdir /lib/modules/3.19.8-yocto-standard/build`
`root@quark:~/rtl8812AU_8821AU_linux-master# make`
`make ARCH=i386 CROSS_COMPILE= -C /lib/modules/3.19.8-yocto-standard/build` `M=/home/root/rtl8812AU_8821AU_linux-master  modules`
`make[1]: Entering directory '/lib/modules/3.19.8-yocto-standard/build'`
`make[1]: *** No rule to make target 'modules'.  Stop.`
`make[1]: Leaving directory '/lib/modules/3.19.8-yocto-standard/build'`
`Makefile:1049: recipe for target 'modules' failed`
`make: *** [modules] Error 2`

What is happening?

I've been reading and apparently need to [install linux-headers](https://www.raspberrypi.org/forums/viewtopic.php?t=67347&p=495080)
with the command:
`apt-get install linux-headers`

but only find to install with apt-get command or via dkms, which are not in this image, only opkg and without any feed, I found this [page](http://alextgalileo.altervista.org/package-repo-configuration-instructions.html) to update the repository, but not even the linux-headers or the apt- get.
, how do I get install linux-headers? I've tried installing apt-get and dkms from opkg but without success.

How do I get install the driver successfully?

A greeting.
AntonioG

**Comment by xbolshe** [comment]
The current image has no Kernel source code. It means that a driver compilation will fail.
For now need to use PC to compile own driver and to create a new Linux image with embedded driver.

BR,
xbolshe

**Comment by AntonioAlgaida** [comment]
What should I do?
Can I crosscompile from the PC and load the driver?

I read [this](https://github.com/ulli-kroll/rtl8821au), but I do not know what parameters write when doing
 `make ARCH="..." CROSS_COMPILE=... KSRC=...`

A greeting.
AntonioG

**Comment by AntonioAlgaida** [comment]
Could you tell me how I can compile and run it?
Thank you very much.
A greeting.

**Comment by xbolshe** [comment]
I guess you may compile it using a source code like https://github.com/xbolshe/galileo-sources/tree/master/iot_1.2.0_kernel_3.19.8 and make own image.
